# $Id$

TESTS += modules/parsers/gas/tests/amd64/gas_amd64_test.sh

EXTRA_DIST += modules/parsers/gas/tests/amd64/gas_amd64_test.sh
EXTRA_DIST += modules/parsers/gas/tests/amd64/riprel.asm
EXTRA_DIST += modules/parsers/gas/tests/amd64/riprel.errwarn
EXTRA_DIST += modules/parsers/gas/tests/amd64/riprel.hex

