# $Id: Makefile.inc 1168 2004-10-31 01:07:52Z peter $

TESTS += modules/objfmts/elf/tests/gas64/elf_gas64_test.sh

EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_test.sh
EXTRA_DIST += modules/objfmts/elf/tests/gas64/crosssect.asm
EXTRA_DIST += modules/objfmts/elf/tests/gas64/crosssect.hex
EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_curpos.asm
EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_curpos.hex
EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_reloc.asm
EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_reloc.hex
EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_ssym.asm
EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_ssym.hex
