# $Id$

TESTS += modules/objfmts/win32/tests/win32_test.sh

EXTRA_DIST += modules/objfmts/win32/tests/export.asm
EXTRA_DIST += modules/objfmts/win32/tests/export.hex
EXTRA_DIST += modules/objfmts/win32/tests/export.errwarn
EXTRA_DIST += modules/objfmts/win32/tests/win32_test.sh
EXTRA_DIST += modules/objfmts/win32/tests/win32-curpos.asm
EXTRA_DIST += modules/objfmts/win32/tests/win32-curpos.hex
EXTRA_DIST += modules/objfmts/win32/tests/win32-curpos.errwarn
EXTRA_DIST += modules/objfmts/win32/tests/win32-overdef.asm
EXTRA_DIST += modules/objfmts/win32/tests/win32-overdef.hex
EXTRA_DIST += modules/objfmts/win32/tests/win32-overdef.errwarn
EXTRA_DIST += modules/objfmts/win32/tests/win32test.c
EXTRA_DIST += modules/objfmts/win32/tests/win32test.asm
EXTRA_DIST += modules/objfmts/win32/tests/win32test.hex
EXTRA_DIST += modules/objfmts/win32/tests/win32test.errwarn
