# $IdPath$

TESTS += modules/objfmts/win32/tests/win32_test.sh

EXTRA_DIST += modules/objfmts/win32/tests/win32_test.sh
EXTRA_DIST += modules/objfmts/win32/tests/win32test.c
EXTRA_DIST += modules/objfmts/win32/tests/win32test.asm
EXTRA_DIST += modules/objfmts/win32/tests/win32test.hex
EXTRA_DIST += modules/objfmts/win32/tests/win32test.errwarn
