# $Id$

TESTS += modules/objfmts/xdf/tests/xdf_test.sh

EXTRA_DIST += modules/objfmts/xdf/tests/xdf_test.sh
EXTRA_DIST += modules/objfmts/xdf/tests/xdflong.asm
EXTRA_DIST += modules/objfmts/xdf/tests/xdflong.hex
EXTRA_DIST += modules/objfmts/xdf/tests/xdflong.errwarn
EXTRA_DIST += modules/objfmts/xdf/tests/xdfprotect.asm
EXTRA_DIST += modules/objfmts/xdf/tests/xdfprotect.hex
EXTRA_DIST += modules/objfmts/xdf/tests/xdfprotect.errwarn
EXTRA_DIST += modules/objfmts/xdf/tests/xdfother.asm
EXTRA_DIST += modules/objfmts/xdf/tests/xdfother.hex
EXTRA_DIST += modules/objfmts/xdf/tests/xdfother.errwarn
EXTRA_DIST += modules/objfmts/xdf/tests/xdf-overdef.asm
EXTRA_DIST += modules/objfmts/xdf/tests/xdf-overdef.hex
EXTRA_DIST += modules/objfmts/xdf/tests/xdf-overdef.errwarn
EXTRA_DIST += modules/objfmts/xdf/tests/xdfvirtual.asm
EXTRA_DIST += modules/objfmts/xdf/tests/xdfvirtual.hex
EXTRA_DIST += modules/objfmts/xdf/tests/xdfvirtual.errwarn
