# $Id$

CHECKFILES  = check/check.c
CHECKFILES += check/check_run.c
CHECKFILES += check/check.h
CHECKFILES += check/check_impl.h
CHECKFILES += check/check_msg.c
CHECKFILES += check/check_msg.h
CHECKFILES += check/check_log.c
CHECKFILES += check/check_log.h
CHECKFILES += check/check_print.c
CHECKFILES += check/check_print.h
CHECKFILES += check/error.c
CHECKFILES += check/error.h
CHECKFILES += check/list.c
CHECKFILES += check/list.h

EXTRA_DIST += check/NEWS
EXTRA_DIST += check/README
