# $IdPath$

CHECKFILES = \
	check/check.c		\
	check/check_run.c	\
	check/check.h		\
	check/check_impl.h	\
	check/check_msg.c	\
	check/check_msg.h	\
	check/check_log.c	\
	check/check_log.h	\
	check/check_print.c	\
	check/check_print.h	\
	check/error.c		\
	check/error.h		\
	check/list.c		\
	check/list.h

EXTRA_DIST += \
	check/NEWS	\
	check/README
