# $IdPath$

TESTS += \
	modules/preprocs/yapp/tests/yapp_test.sh

EXTRA_DIST += \
	modules/preprocs/yapp/tests/Makefile.inc	\
	modules/preprocs/yapp/tests/yapp_test.sh	\
	modules/preprocs/yapp/tests/raw.asm		\
	modules/preprocs/yapp/tests/raw.pre		\
	modules/preprocs/yapp/tests/comment.asm		\
	modules/preprocs/yapp/tests/comment.pre		\
	modules/preprocs/yapp/tests/define.asm		\
	modules/preprocs/yapp/tests/define.pre		\
	modules/preprocs/yapp/tests/ddefine.asm		\
	modules/preprocs/yapp/tests/ddefine.pre		\
	modules/preprocs/yapp/tests/rdefine.asm		\
	modules/preprocs/yapp/tests/rdefine.pre		\
	modules/preprocs/yapp/tests/pdefine.asm		\
	modules/preprocs/yapp/tests/pdefine.pre		\
	modules/preprocs/yapp/tests/ifdef.asm		\
	modules/preprocs/yapp/tests/ifdef.pre		\
	modules/preprocs/yapp/tests/include.asm		\
	modules/preprocs/yapp/tests/include.pre		\
	modules/preprocs/yapp/tests/rinclude.asm	\
	modules/preprocs/yapp/tests/rinclude.pre	\
	modules/preprocs/yapp/tests/params.asm		\
	modules/preprocs/yapp/tests/params.pre
