# $IdPath$

TESTS += \
	src/preprocs/yapp/tests/yapp_test.sh

EXTRA_DIST += \
	src/preprocs/yapp/tests/Makefile.inc \
	src/preprocs/yapp/tests/yapp_test.sh \
	src/preprocs/yapp/tests/raw.asm \
	src/preprocs/yapp/tests/raw.pre \
	src/preprocs/yapp/tests/comment.asm \
	src/preprocs/yapp/tests/comment.pre \
	src/preprocs/yapp/tests/define.asm \
	src/preprocs/yapp/tests/define.pre \
	src/preprocs/yapp/tests/ddefine.asm \
	src/preprocs/yapp/tests/ddefine.pre \
	src/preprocs/yapp/tests/rdefine.asm \
	src/preprocs/yapp/tests/rdefine.pre \
	src/preprocs/yapp/tests/pdefine.asm \
	src/preprocs/yapp/tests/pdefine.pre \
	src/preprocs/yapp/tests/ifdef.asm \
	src/preprocs/yapp/tests/ifdef.pre \
	src/preprocs/yapp/tests/include.asm \
	src/preprocs/yapp/tests/include.pre \
	src/preprocs/yapp/tests/rinclude.asm \
	src/preprocs/yapp/tests/rinclude.pre \
	src/preprocs/yapp/tests/params.asm \
	src/preprocs/yapp/tests/params.pre
