/* Generated by re2c 0.9.1-C on Sat Oct  8 22:50:57 2005
 */
#line 1 "scanner.re"
#include <stdlib.h>
#include <string.h>
#include "tools/re2c/scanner.h"
#include "tools/re2c/parse.h"
#include "tools/re2c/globals.h"
#include "re2c-parser.h"

#ifndef MAX
#define MAX(a,b) (((a)>(b))?(a):(b))
#endif

#define	BSIZE	8192

#define	YYCTYPE		unsigned char
#define	YYCURSOR	cursor
#define	YYLIMIT		s->lim
#define	YYMARKER	s->ptr
#define	YYFILL(n)	{cursor = fill(s, cursor);}

#define	RETURN(i)	{s->cur = cursor; return i;}

static unsigned char *fill(Scanner*, unsigned char*);

void
Scanner_init(Scanner *s, FILE *i)
{
    s->in = i;
    s->bot = s->tok = s->ptr = s->cur = s->pos = s->lim = s->top =
	     s->eof = NULL;
    s->tchar = s->tline = 0;
    s->cline = 1;
}

static unsigned char *
fill(Scanner *s, unsigned char *cursor)
{
    if(!s->eof){
	unsigned int cnt = s->tok - s->bot;
	if(cnt){
	    memcpy(s->bot, s->tok, s->lim - s->tok);
	    s->tok = s->bot;
	    s->ptr -= cnt;
	    cursor -= cnt;
	    s->pos -= cnt;
	    s->lim -= cnt;
	}
	if((s->top - s->lim) < BSIZE){
	    unsigned char *buf = malloc(((s->lim - s->bot) + BSIZE));
	    memcpy(buf, s->tok, s->lim - s->tok);
	    s->tok = buf;
	    s->ptr = &buf[s->ptr - s->bot];
	    cursor = &buf[cursor - s->bot];
	    s->pos = &buf[s->pos - s->bot];
	    s->lim = &buf[s->lim - s->bot];
	    s->top = &s->lim[BSIZE];
	    if (s->bot)
		free(s->bot);
	    s->bot = buf;
	}
	if((cnt = fread(s->lim, 1, BSIZE, s->in)) != BSIZE){
	    s->eof = &s->lim[cnt]; *s->eof++ = '\n';
	}
	s->lim += cnt;
    }
    return cursor;
}

#line 77 "scanner.re"


int
Scanner_echo(Scanner *s, FILE *out)
{
    unsigned char *cursor = s->cur;

    /* Catch EOF */
    if (s->eof && cursor == s->eof)
	return 0;

    s->tok = cursor;
echo:

#line 87 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy0;
	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy4;
	if(yych != '/')	goto yy6;
	goto yy2;
yy2:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '*')	goto yy7;
	goto yy3;
yy3:
#line 98 "scanner.re"
{ goto echo; }
#line 106 "scanner.c"
yy4:	yych = *++YYCURSOR;
	goto yy5;
yy5:
#line 94 "scanner.re"
{ if(cursor == s->eof) RETURN(0);
				  fwrite(s->tok, 1, cursor - s->tok, out);
				  s->tok = s->pos = cursor; s->cline++; oline++;
				  goto echo; }
#line 115 "scanner.c"
yy6:	yych = *++YYCURSOR;
	goto yy3;
yy7:	yych = *++YYCURSOR;
	if(yych == '!')	goto yy9;
	goto yy8;
yy8:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy3;
	}
yy9:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy8;
	goto yy10;
yy10:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy8;
	goto yy11;
yy11:	yych = *++YYCURSOR;
	if(yych != '2')	goto yy8;
	goto yy12;
yy12:	yych = *++YYCURSOR;
	if(yych != 'c')	goto yy8;
	goto yy13;
yy13:	yych = *++YYCURSOR;
	goto yy14;
yy14:
#line 91 "scanner.re"
{ fwrite(s->tok, 1, &cursor[-7] - s->tok, out);
				  s->tok = cursor;
				  RETURN(1); }
#line 144 "scanner.c"
}
#line 99 "scanner.re"

}


int
Scanner_scan(Scanner *s)
{
    unsigned char *cursor = s->cur;
    unsigned int depth;

scan:
    s->tchar = cursor - s->pos;
    s->tline = s->cline;
    s->tok = cursor;

#line 162 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy15;
	++YYCURSOR;
yy15:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '/'){
		if(yych <= '"'){
			if(yych <= '\n'){
				if(yych <= '\b')	goto yy37;
				if(yych <= '\t')	goto yy33;
				goto yy35;
			} else {
				if(yych == ' ')	goto yy33;
				if(yych <= '!')	goto yy37;
				goto yy23;
			}
		} else {
			if(yych <= ')'){
				if(yych <= '&')	goto yy37;
				if(yych <= '\'')	goto yy25;
				goto yy29;
			} else {
				if(yych <= '*')	goto yy21;
				if(yych <= '+')	goto yy30;
				if(yych <= '.')	goto yy37;
				goto yy19;
			}
		}
	} else {
		if(yych <= '@'){
			if(yych <= '<'){
				if(yych == ';')	goto yy29;
				goto yy37;
			} else {
				if(yych <= '=')	goto yy29;
				if(yych == '?')	goto yy30;
				goto yy37;
			}
		} else {
			if(yych <= '`'){
				if(yych <= 'Z')	goto yy31;
				if(yych <= '[')	goto yy27;
				if(yych <= '\\')	goto yy29;
				goto yy37;
			} else {
				if(yych <= 'z')	goto yy31;
				if(yych <= '{')	goto yy17;
				if(yych <= '|')	goto yy29;
				goto yy37;
			}
		}
	}
yy17:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '/')	goto yy18;
	if(yych <= '9')	goto yy63;
	goto yy18;
yy18:
#line 114 "scanner.re"
{ depth = 1;
				  goto code;
				}
#line 228 "scanner.c"
yy19:	yych = *++YYCURSOR;
	if(yych == '*')	goto yy61;
	goto yy20;
yy20:
#line 140 "scanner.re"
{ RETURN(*s->tok); }
#line 235 "scanner.c"
yy21:	yych = *++YYCURSOR;
	if(yych == '/')	goto yy59;
	goto yy22;
yy22:
#line 142 "scanner.re"
{ yylval.op = *s->tok;
				  RETURN(CLOSE); }
#line 243 "scanner.c"
yy23:	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych != '\n')	goto yy55;
	goto yy24;
yy24:
#line 131 "scanner.re"
{ Scanner_fatal(s, "unterminated string constant (missing \")"); }
#line 251 "scanner.c"
yy25:	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych != '\n')	goto yy50;
	goto yy26;
yy26:
#line 132 "scanner.re"
{ Scanner_fatal(s, "unterminated string constant (missing ')"); }
#line 259 "scanner.c"
yy27:	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych != '\n')	goto yy44;
	goto yy28;
yy28:
#line 138 "scanner.re"
{ Scanner_fatal(s, "unterminated range (missing ])"); }
#line 267 "scanner.c"
yy29:	yych = *++YYCURSOR;
	goto yy20;
yy30:	yych = *++YYCURSOR;
	goto yy22;
yy31:	yych = *++YYCURSOR;
	goto yy42;
yy32:
#line 157 "scanner.re"
{ SubStr substr;
				  s->cur = cursor;
				  substr = Scanner_token(s);
				  yylval.symbol = Symbol_find(&substr);
				  return ID; }
#line 281 "scanner.c"
yy33:	yych = *++YYCURSOR;
	goto yy40;
yy34:
#line 163 "scanner.re"
{ goto scan; }
#line 287 "scanner.c"
yy35:	yych = *++YYCURSOR;
	goto yy36;
yy36:
#line 165 "scanner.re"
{ if(cursor == s->eof) RETURN(0);
				  s->pos = cursor; s->cline++;
				  goto scan;
	    			}
#line 296 "scanner.c"
yy37:	yych = *++YYCURSOR;
	goto yy38;
yy38:
#line 170 "scanner.re"
{ fprintf(stderr, "unexpected character: '%c'\n", *s->tok);
				  goto scan;
				}
#line 304 "scanner.c"
yy39:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy40;
yy40:	if(yych == '\t')	goto yy39;
	if(yych == ' ')	goto yy39;
	goto yy34;
yy41:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy42;
yy42:	if(yych <= '@'){
		if(yych <= '/')	goto yy32;
		if(yych <= '9')	goto yy41;
		goto yy32;
	} else {
		if(yych <= 'Z')	goto yy41;
		if(yych <= '`')	goto yy32;
		if(yych <= 'z')	goto yy41;
		goto yy32;
	}
yy43:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy44;
yy44:	if(yych <= '['){
		if(yych != '\n')	goto yy43;
		goto yy45;
	} else {
		if(yych <= '\\')	goto yy46;
		if(yych <= ']')	goto yy47;
		goto yy43;
	}
yy45:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy18;
	case 1:	goto yy24;
	case 2:	goto yy26;
	case 3:	goto yy28;
	}
yy46:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy45;
	goto yy43;
yy47:	yych = *++YYCURSOR;
	goto yy48;
yy48:
#line 134 "scanner.re"
{ s->cur = cursor;
				  yylval.regexp = ranToRE(Scanner_token(s));
				  return RANGE; }
#line 357 "scanner.c"
yy49:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy50;
yy50:	if(yych <= '&'){
		if(yych == '\n')	goto yy45;
		goto yy49;
	} else {
		if(yych <= '\'')	goto yy52;
		if(yych != '\\')	goto yy49;
		goto yy51;
	}
yy51:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy45;
	goto yy49;
yy52:	yych = *++YYCURSOR;
	goto yy53;
yy53:
#line 127 "scanner.re"
{ s->cur = cursor;
				  yylval.regexp = strToCaseInsensitiveRE(Scanner_token(s));
				  return STRING; }
#line 382 "scanner.c"
yy54:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy55;
yy55:	if(yych <= '!'){
		if(yych == '\n')	goto yy45;
		goto yy54;
	} else {
		if(yych <= '"')	goto yy57;
		if(yych != '\\')	goto yy54;
		goto yy56;
	}
yy56:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy45;
	goto yy54;
yy57:	yych = *++YYCURSOR;
	goto yy58;
yy58:
#line 123 "scanner.re"
{ s->cur = cursor;
				  yylval.regexp = strToRE(Scanner_token(s));
				  return STRING; }
#line 407 "scanner.c"
yy59:	yych = *++YYCURSOR;
	goto yy60;
yy60:
#line 120 "scanner.re"
{ s->tok = cursor;
				  RETURN(0); }
#line 414 "scanner.c"
yy61:	yych = *++YYCURSOR;
	goto yy62;
yy62:
#line 117 "scanner.re"
{ depth = 1;
				  goto comment; }
#line 421 "scanner.c"
yy63:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy64;
yy64:	if(yych <= '/'){
		if(yych == ',')	goto yy67;
		goto yy45;
	} else {
		if(yych <= '9')	goto yy63;
		if(yych != '}')	goto yy45;
		goto yy65;
	}
yy65:	yych = *++YYCURSOR;
	goto yy66;
yy66:
#line 145 "scanner.re"
{ yylval.extop.minsize = atoi((char *)s->tok+1);
				  yylval.extop.maxsize = atoi((char *)s->tok+1);
				  RETURN(CLOSESIZE); }
#line 441 "scanner.c"
yy67:	yych = *++YYCURSOR;
	if(yych != '}')	goto yy71;
	goto yy68;
yy68:	yych = *++YYCURSOR;
	goto yy69;
yy69:
#line 153 "scanner.re"
{ yylval.extop.minsize = atoi((char *)s->tok+1);
				  yylval.extop.maxsize = -1;
				  RETURN(CLOSESIZE); }
#line 452 "scanner.c"
yy70:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy71;
yy71:	if(yych <= '/')	goto yy45;
	if(yych <= '9')	goto yy70;
	if(yych != '}')	goto yy45;
	goto yy72;
yy72:	yych = *++YYCURSOR;
	goto yy73;
yy73:
#line 149 "scanner.re"
{ yylval.extop.minsize = atoi((char *)s->tok+1);
				  yylval.extop.maxsize = MAX(yylval.extop.minsize,atoi(strchr((char *)s->tok, ',')+1));
				  RETURN(CLOSESIZE); }
#line 468 "scanner.c"
}
#line 173 "scanner.re"


code:

#line 475 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy74;
	++YYCURSOR;
yy74:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '&'){
		if(yych <= '\n'){
			if(yych <= '\t')	goto yy82;
			goto yy80;
		} else {
			if(yych == '"')	goto yy84;
			goto yy82;
		}
	} else {
		if(yych <= '{'){
			if(yych <= '\'')	goto yy85;
			if(yych <= 'z')	goto yy82;
			goto yy78;
		} else {
			if(yych != '}')	goto yy82;
			goto yy76;
		}
	}
yy76:	yych = *++YYCURSOR;
	goto yy77;
yy77:
#line 177 "scanner.re"
{ if(--depth == 0){
					s->cur = cursor;
					yylval.token = Token_new(Scanner_token(s), s->tline);
					return CODE;
				  }
				  goto code; }
#line 512 "scanner.c"
yy78:	yych = *++YYCURSOR;
	goto yy79;
yy79:
#line 183 "scanner.re"
{ ++depth;
				  goto code; }
#line 519 "scanner.c"
yy80:	yych = *++YYCURSOR;
	goto yy81;
yy81:
#line 185 "scanner.re"
{ if(cursor == s->eof) Scanner_fatal(s, "missing '}'");
				  s->pos = cursor; s->cline++;
				  goto code;
				}
#line 528 "scanner.c"
yy82:	yych = *++YYCURSOR;
	goto yy83;
yy83:
#line 189 "scanner.re"
{ goto code; }
#line 534 "scanner.c"
yy84:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '\n')	goto yy83;
	goto yy91;
yy85:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '\n')	goto yy83;
	goto yy87;
yy86:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy87;
yy87:	if(yych <= '&'){
		if(yych != '\n')	goto yy86;
		goto yy88;
	} else {
		if(yych <= '\'')	goto yy82;
		if(yych == '\\')	goto yy89;
		goto yy86;
	}
yy88:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy83;
	}
yy89:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy88;
	goto yy86;
yy90:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy91;
yy91:	if(yych <= '!'){
		if(yych == '\n')	goto yy88;
		goto yy90;
	} else {
		if(yych <= '"')	goto yy82;
		if(yych != '\\')	goto yy90;
		goto yy92;
	}
yy92:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy88;
	goto yy90;
}
#line 190 "scanner.re"


comment:

#line 587 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy93;
	++YYCURSOR;
yy93:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= ')'){
		if(yych == '\n')	goto yy98;
		goto yy100;
	} else {
		if(yych <= '*')	goto yy95;
		if(yych == '/')	goto yy97;
		goto yy100;
	}
yy95:	yych = *++YYCURSOR;
	if(yych == '/')	goto yy103;
	goto yy96;
yy96:
#line 204 "scanner.re"
{ goto comment; }
#line 610 "scanner.c"
yy97:	yych = *++YYCURSOR;
	if(yych == '*')	goto yy101;
	goto yy96;
yy98:	yych = *++YYCURSOR;
	goto yy99;
yy99:
#line 200 "scanner.re"
{ if(cursor == s->eof) RETURN(0);
				  s->tok = s->pos = cursor; s->cline++;
				  goto comment;
				}
#line 622 "scanner.c"
yy100:	yych = *++YYCURSOR;
	goto yy96;
yy101:	yych = *++YYCURSOR;
	goto yy102;
yy102:
#line 198 "scanner.re"
{ ++depth;
				  goto comment; }
#line 631 "scanner.c"
yy103:	yych = *++YYCURSOR;
	goto yy104;
yy104:
#line 194 "scanner.re"
{ if(--depth == 0)
					goto scan;
				    else
					goto comment; }
#line 640 "scanner.c"
}
#line 205 "scanner.re"

}

void
Scanner_fatal(Scanner *s, const char *msg)
{
    fprintf(stderr, "line %d, column %d: %s\n", s->tline, s->tchar + 1, msg);
    exit(1);
}
