/* Generated by re2c 0.9.1-C on Sun Oct  9 00:12:08 2005
 */
#line 1 "scanner.re"
#include <stdlib.h>
#include <string.h>
#include "tools/re2c/scanner.h"
#include "tools/re2c/parse.h"
#include "tools/re2c/globals.h"
#include "re2c-parser.h"

#ifndef MAX
#define MAX(a,b) (((a)>(b))?(a):(b))
#endif

#define	BSIZE	8192

#define	YYCTYPE		unsigned char
#define	YYCURSOR	cursor
#define	YYLIMIT		s->lim
#define	YYMARKER	s->ptr
#define	YYFILL(n)	{cursor = fill(s, cursor);}

#define	RETURN(i)	{s->cur = cursor; return i;}

static unsigned char *fill(Scanner*, unsigned char*);

void
Scanner_init(Scanner *s, FILE *i)
{
    s->in = i;
    s->bot = s->tok = s->ptr = s->cur = s->pos = s->lim = s->top =
	     s->eof = NULL;
    s->tchar = s->tline = 0;
    s->cline = 1;
}

static unsigned char *
fill(Scanner *s, unsigned char *cursor)
{
    if(!s->eof){
	unsigned int cnt = s->tok - s->bot;
	if(cnt){
	    memcpy(s->bot, s->tok, s->lim - s->tok);
	    s->tok = s->bot;
	    s->ptr -= cnt;
	    cursor -= cnt;
	    s->pos -= cnt;
	    s->lim -= cnt;
	}
	if((s->top - s->lim) < BSIZE){
	    unsigned char *buf = malloc(((s->lim - s->bot) + BSIZE));
	    memcpy(buf, s->tok, s->lim - s->tok);
	    s->tok = buf;
	    s->ptr = &buf[s->ptr - s->bot];
	    cursor = &buf[cursor - s->bot];
	    s->pos = &buf[s->pos - s->bot];
	    s->lim = &buf[s->lim - s->bot];
	    s->top = &s->lim[BSIZE];
	    if (s->bot)
		free(s->bot);
	    s->bot = buf;
	}
	if((cnt = fread(s->lim, 1, BSIZE, s->in)) != BSIZE){
	    s->eof = &s->lim[cnt]; *s->eof++ = '\0';
	}
	s->lim += cnt;
    }
    return cursor;
}

#line 78 "scanner.re"


int
Scanner_echo(Scanner *s, FILE *out)
{
    unsigned char *cursor = s->cur;

    /* Catch EOF */
    if (s->eof && cursor == s->eof)
	return 0;

    s->tok = cursor;
echo:

#line 87 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy0;
	if(yych <= '\n'){
		if(yych <= '\000')	goto yy6;
		if(yych <= '\t')	goto yy8;
		goto yy4;
	} else {
		if(yych != '/')	goto yy8;
		goto yy2;
	}
	if(yych == '*')	goto yy9;
	goto yy3;
	goto yy5;
	goto yy7;
	goto yy3;
	if(yych == '!')	goto yy11;
	goto yy10;
	if(yych != 'r')	goto yy10;
	goto yy12;
	if(yych != 'e')	goto yy10;
	goto yy13;
	if(yych != '2')	goto yy10;
	goto yy14;
	if(yych != 'c')	goto yy10;
	goto yy15;
	goto yy16;
	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
	if(yych <= '\n'){
		if(yych <= '\000')	goto yy6;
		if(yych <= '\t')	goto yy8;
		goto yy4;
	} else {
		if(yych != '/')	goto yy8;
		goto yy2;
	}
yy2:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '*')	goto yy9;
	goto yy3;
yy3:
#line 100 "scanner.re"
{ goto echo; }
#line 111 "scanner.c"
yy4:	yych = *++YYCURSOR;
	goto yy5;
yy5:
#line 95 "scanner.re"
{ fwrite(s->tok, 1, cursor - s->tok, out);
				  s->tok = s->pos = cursor; s->cline++; oline++;
				  goto echo; }
#line 119 "scanner.c"
yy6:	yych = *++YYCURSOR;
	goto yy7;
yy7:
#line 98 "scanner.re"
{ fwrite(s->tok, 1, cursor - s->tok - 1, out); /* -1 so we don't write out the \0 */
				  if(cursor == s->eof) { RETURN(0); } }
#line 126 "scanner.c"
yy8:	yych = *++YYCURSOR;
	goto yy3;
yy9:	yych = *++YYCURSOR;
	if(yych == '!')	goto yy11;
	goto yy10;
yy10:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy3;
	}
yy11:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy10;
	goto yy12;
yy12:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy10;
	goto yy13;
yy13:	yych = *++YYCURSOR;
	if(yych != '2')	goto yy10;
	goto yy14;
yy14:	yych = *++YYCURSOR;
	if(yych != 'c')	goto yy10;
	goto yy15;
yy15:	yych = *++YYCURSOR;
	goto yy16;
yy16:
#line 92 "scanner.re"
{ fwrite(s->tok, 1, &cursor[-7] - s->tok, out);
				  s->tok = cursor;
				  RETURN(1); }
#line 155 "scanner.c"
}
#line 101 "scanner.re"

}


int
Scanner_scan(Scanner *s)
{
    unsigned char *cursor = s->cur;
    unsigned int depth;

scan:
    s->tchar = cursor - s->pos;
    s->tline = s->cline;
    s->tok = cursor;

#line 173 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy17;
	if(yych <= '/'){
		if(yych <= '"'){
			if(yych <= '\n'){
				if(yych <= '\b')	goto yy39;
				if(yych <= '\t')	goto yy35;
				goto yy37;
			} else {
				if(yych == ' ')	goto yy35;
				if(yych <= '!')	goto yy39;
				goto yy25;
			}
		} else {
			if(yych <= ')'){
				if(yych <= '&')	goto yy39;
				if(yych <= '\'')	goto yy27;
				goto yy31;
			} else {
				if(yych <= '*')	goto yy23;
				if(yych <= '+')	goto yy32;
				if(yych <= '.')	goto yy39;
				goto yy21;
			}
		}
	} else {
		if(yych <= '@'){
			if(yych <= '<'){
				if(yych == ';')	goto yy31;
				goto yy39;
			} else {
				if(yych <= '=')	goto yy31;
				if(yych == '?')	goto yy32;
				goto yy39;
			}
		} else {
			if(yych <= '`'){
				if(yych <= 'Z')	goto yy33;
				if(yych <= '[')	goto yy29;
				if(yych <= '\\')	goto yy31;
				goto yy39;
			} else {
				if(yych <= 'z')	goto yy33;
				if(yych <= '{')	goto yy19;
				if(yych <= '|')	goto yy31;
				goto yy39;
			}
		}
	}
	if(yych <= '/')	goto yy20;
	if(yych <= '9')	goto yy65;
	goto yy20;
	if(yych == '*')	goto yy63;
	goto yy22;
	if(yych == '/')	goto yy61;
	goto yy24;
	if(yych != '\n')	goto yy57;
	goto yy26;
	if(yych != '\n')	goto yy52;
	goto yy28;
	if(yych != '\n')	goto yy46;
	goto yy30;
	goto yy22;
	goto yy24;
	goto yy44;
	goto yy42;
	goto yy38;
	goto yy40;
	goto yy42;
	if(yych == '\t')	goto yy41;
	if(yych == ' ')	goto yy41;
	goto yy36;
	goto yy44;
	if(yych <= '@'){
		if(yych <= '/')	goto yy34;
		if(yych <= '9')	goto yy43;
		goto yy34;
	} else {
		if(yych <= 'Z')	goto yy43;
		if(yych <= '`')	goto yy34;
		if(yych <= 'z')	goto yy43;
		goto yy34;
	}
	goto yy46;
	if(yych <= '['){
		if(yych != '\n')	goto yy45;
		goto yy47;
	} else {
		if(yych <= '\\')	goto yy48;
		if(yych <= ']')	goto yy49;
		goto yy45;
	}
	if(yych == '\n')	goto yy47;
	goto yy45;
	goto yy50;
	goto yy52;
	if(yych <= '&'){
		if(yych == '\n')	goto yy47;
		goto yy51;
	} else {
		if(yych <= '\'')	goto yy54;
		if(yych != '\\')	goto yy51;
		goto yy53;
	}
	if(yych == '\n')	goto yy47;
	goto yy51;
	goto yy55;
	goto yy57;
	if(yych <= '!'){
		if(yych == '\n')	goto yy47;
		goto yy56;
	} else {
		if(yych <= '"')	goto yy59;
		if(yych != '\\')	goto yy56;
		goto yy58;
	}
	if(yych == '\n')	goto yy47;
	goto yy56;
	goto yy60;
	goto yy62;
	goto yy64;
	goto yy66;
	if(yych <= '/'){
		if(yych == ',')	goto yy69;
		goto yy47;
	} else {
		if(yych <= '9')	goto yy65;
		if(yych != '}')	goto yy47;
		goto yy67;
	}
	goto yy68;
	if(yych != '}')	goto yy73;
	goto yy70;
	goto yy71;
	goto yy73;
	if(yych <= '/')	goto yy47;
	if(yych <= '9')	goto yy72;
	if(yych != '}')	goto yy47;
	goto yy74;
	goto yy75;
	++YYCURSOR;
yy17:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '/'){
		if(yych <= '"'){
			if(yych <= '\n'){
				if(yych <= '\b')	goto yy39;
				if(yych <= '\t')	goto yy35;
				goto yy37;
			} else {
				if(yych == ' ')	goto yy35;
				if(yych <= '!')	goto yy39;
				goto yy25;
			}
		} else {
			if(yych <= ')'){
				if(yych <= '&')	goto yy39;
				if(yych <= '\'')	goto yy27;
				goto yy31;
			} else {
				if(yych <= '*')	goto yy23;
				if(yych <= '+')	goto yy32;
				if(yych <= '.')	goto yy39;
				goto yy21;
			}
		}
	} else {
		if(yych <= '@'){
			if(yych <= '<'){
				if(yych == ';')	goto yy31;
				goto yy39;
			} else {
				if(yych <= '=')	goto yy31;
				if(yych == '?')	goto yy32;
				goto yy39;
			}
		} else {
			if(yych <= '`'){
				if(yych <= 'Z')	goto yy33;
				if(yych <= '[')	goto yy29;
				if(yych <= '\\')	goto yy31;
				goto yy39;
			} else {
				if(yych <= 'z')	goto yy33;
				if(yych <= '{')	goto yy19;
				if(yych <= '|')	goto yy31;
				goto yy39;
			}
		}
	}
yy19:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '/')	goto yy20;
	if(yych <= '9')	goto yy65;
	goto yy20;
yy20:
#line 116 "scanner.re"
{ depth = 1;
				  goto code;
				}
#line 239 "scanner.c"
yy21:	yych = *++YYCURSOR;
	if(yych == '*')	goto yy63;
	goto yy22;
yy22:
#line 142 "scanner.re"
{ RETURN(*s->tok); }
#line 246 "scanner.c"
yy23:	yych = *++YYCURSOR;
	if(yych == '/')	goto yy61;
	goto yy24;
yy24:
#line 144 "scanner.re"
{ yylval.op = *s->tok;
				  RETURN(CLOSE); }
#line 254 "scanner.c"
yy25:	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych != '\n')	goto yy57;
	goto yy26;
yy26:
#line 133 "scanner.re"
{ Scanner_fatal(s, "unterminated string constant (missing \")"); }
#line 262 "scanner.c"
yy27:	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych != '\n')	goto yy52;
	goto yy28;
yy28:
#line 134 "scanner.re"
{ Scanner_fatal(s, "unterminated string constant (missing ')"); }
#line 270 "scanner.c"
yy29:	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych != '\n')	goto yy46;
	goto yy30;
yy30:
#line 140 "scanner.re"
{ Scanner_fatal(s, "unterminated range (missing ])"); }
#line 278 "scanner.c"
yy31:	yych = *++YYCURSOR;
	goto yy22;
yy32:	yych = *++YYCURSOR;
	goto yy24;
yy33:	yych = *++YYCURSOR;
	goto yy44;
yy34:
#line 159 "scanner.re"
{ SubStr substr;
				  s->cur = cursor;
				  substr = Scanner_token(s);
				  yylval.symbol = Symbol_find(&substr);
				  return ID; }
#line 292 "scanner.c"
yy35:	yych = *++YYCURSOR;
	goto yy42;
yy36:
#line 165 "scanner.re"
{ goto scan; }
#line 298 "scanner.c"
yy37:	yych = *++YYCURSOR;
	goto yy38;
yy38:
#line 167 "scanner.re"
{ if(cursor == s->eof) RETURN(0);
				  s->pos = cursor; s->cline++;
				  goto scan;
	    			}
#line 307 "scanner.c"
yy39:	yych = *++YYCURSOR;
	goto yy40;
yy40:
#line 172 "scanner.re"
{ fprintf(stderr, "unexpected character: '%c'\n", *s->tok);
				  goto scan;
				}
#line 315 "scanner.c"
yy41:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy42;
yy42:	if(yych == '\t')	goto yy41;
	if(yych == ' ')	goto yy41;
	goto yy36;
yy43:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy44;
yy44:	if(yych <= '@'){
		if(yych <= '/')	goto yy34;
		if(yych <= '9')	goto yy43;
		goto yy34;
	} else {
		if(yych <= 'Z')	goto yy43;
		if(yych <= '`')	goto yy34;
		if(yych <= 'z')	goto yy43;
		goto yy34;
	}
yy45:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy46;
yy46:	if(yych <= '['){
		if(yych != '\n')	goto yy45;
		goto yy47;
	} else {
		if(yych <= '\\')	goto yy48;
		if(yych <= ']')	goto yy49;
		goto yy45;
	}
yy47:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy20;
	case 1:	goto yy26;
	case 2:	goto yy28;
	case 3:	goto yy30;
	}
yy48:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy47;
	goto yy45;
yy49:	yych = *++YYCURSOR;
	goto yy50;
yy50:
#line 136 "scanner.re"
{ s->cur = cursor;
				  yylval.regexp = ranToRE(Scanner_token(s));
				  return RANGE; }
#line 368 "scanner.c"
yy51:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy52;
yy52:	if(yych <= '&'){
		if(yych == '\n')	goto yy47;
		goto yy51;
	} else {
		if(yych <= '\'')	goto yy54;
		if(yych != '\\')	goto yy51;
		goto yy53;
	}
yy53:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy47;
	goto yy51;
yy54:	yych = *++YYCURSOR;
	goto yy55;
yy55:
#line 129 "scanner.re"
{ s->cur = cursor;
				  yylval.regexp = strToCaseInsensitiveRE(Scanner_token(s));
				  return STRING; }
#line 393 "scanner.c"
yy56:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy57;
yy57:	if(yych <= '!'){
		if(yych == '\n')	goto yy47;
		goto yy56;
	} else {
		if(yych <= '"')	goto yy59;
		if(yych != '\\')	goto yy56;
		goto yy58;
	}
yy58:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy47;
	goto yy56;
yy59:	yych = *++YYCURSOR;
	goto yy60;
yy60:
#line 125 "scanner.re"
{ s->cur = cursor;
				  yylval.regexp = strToRE(Scanner_token(s));
				  return STRING; }
#line 418 "scanner.c"
yy61:	yych = *++YYCURSOR;
	goto yy62;
yy62:
#line 122 "scanner.re"
{ s->tok = cursor;
				  RETURN(0); }
#line 425 "scanner.c"
yy63:	yych = *++YYCURSOR;
	goto yy64;
yy64:
#line 119 "scanner.re"
{ depth = 1;
				  goto comment; }
#line 432 "scanner.c"
yy65:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy66;
yy66:	if(yych <= '/'){
		if(yych == ',')	goto yy69;
		goto yy47;
	} else {
		if(yych <= '9')	goto yy65;
		if(yych != '}')	goto yy47;
		goto yy67;
	}
yy67:	yych = *++YYCURSOR;
	goto yy68;
yy68:
#line 147 "scanner.re"
{ yylval.extop.minsize = atoi((char *)s->tok+1);
				  yylval.extop.maxsize = atoi((char *)s->tok+1);
				  RETURN(CLOSESIZE); }
#line 452 "scanner.c"
yy69:	yych = *++YYCURSOR;
	if(yych != '}')	goto yy73;
	goto yy70;
yy70:	yych = *++YYCURSOR;
	goto yy71;
yy71:
#line 155 "scanner.re"
{ yylval.extop.minsize = atoi((char *)s->tok+1);
				  yylval.extop.maxsize = -1;
				  RETURN(CLOSESIZE); }
#line 463 "scanner.c"
yy72:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy73;
yy73:	if(yych <= '/')	goto yy47;
	if(yych <= '9')	goto yy72;
	if(yych != '}')	goto yy47;
	goto yy74;
yy74:	yych = *++YYCURSOR;
	goto yy75;
yy75:
#line 151 "scanner.re"
{ yylval.extop.minsize = atoi((char *)s->tok+1);
				  yylval.extop.maxsize = MAX(yylval.extop.minsize,atoi(strchr((char *)s->tok, ',')+1));
				  RETURN(CLOSESIZE); }
#line 479 "scanner.c"
}
#line 175 "scanner.re"


code:

#line 486 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy76;
	if(yych <= '&'){
		if(yych <= '\n'){
			if(yych <= '\t')	goto yy84;
			goto yy82;
		} else {
			if(yych == '"')	goto yy86;
			goto yy84;
		}
	} else {
		if(yych <= '{'){
			if(yych <= '\'')	goto yy87;
			if(yych <= 'z')	goto yy84;
			goto yy80;
		} else {
			if(yych != '}')	goto yy84;
			goto yy78;
		}
	}
	goto yy79;
	goto yy81;
	goto yy83;
	goto yy85;
	if(yych == '\n')	goto yy85;
	goto yy93;
	if(yych == '\n')	goto yy85;
	goto yy89;
	goto yy89;
	if(yych <= '&'){
		if(yych != '\n')	goto yy88;
		goto yy90;
	} else {
		if(yych <= '\'')	goto yy84;
		if(yych == '\\')	goto yy91;
		goto yy88;
	}
	if(yych == '\n')	goto yy90;
	goto yy88;
	goto yy93;
	if(yych <= '!'){
		if(yych == '\n')	goto yy90;
		goto yy92;
	} else {
		if(yych <= '"')	goto yy84;
		if(yych != '\\')	goto yy92;
		goto yy94;
	}
	if(yych == '\n')	goto yy90;
	goto yy92;
	++YYCURSOR;
yy76:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '&'){
		if(yych <= '\n'){
			if(yych <= '\t')	goto yy84;
			goto yy82;
		} else {
			if(yych == '"')	goto yy86;
			goto yy84;
		}
	} else {
		if(yych <= '{'){
			if(yych <= '\'')	goto yy87;
			if(yych <= 'z')	goto yy84;
			goto yy80;
		} else {
			if(yych != '}')	goto yy84;
			goto yy78;
		}
	}
yy78:	yych = *++YYCURSOR;
	goto yy79;
yy79:
#line 179 "scanner.re"
{ if(--depth == 0){
					s->cur = cursor;
					yylval.token = Token_new(Scanner_token(s), s->tline);
					return CODE;
				  }
				  goto code; }
#line 523 "scanner.c"
yy80:	yych = *++YYCURSOR;
	goto yy81;
yy81:
#line 185 "scanner.re"
{ ++depth;
				  goto code; }
#line 530 "scanner.c"
yy82:	yych = *++YYCURSOR;
	goto yy83;
yy83:
#line 187 "scanner.re"
{ if(cursor == s->eof) Scanner_fatal(s, "missing '}'");
				  s->pos = cursor; s->cline++;
				  goto code;
				}
#line 539 "scanner.c"
yy84:	yych = *++YYCURSOR;
	goto yy85;
yy85:
#line 191 "scanner.re"
{ goto code; }
#line 545 "scanner.c"
yy86:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '\n')	goto yy85;
	goto yy93;
yy87:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '\n')	goto yy85;
	goto yy89;
yy88:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy89;
yy89:	if(yych <= '&'){
		if(yych != '\n')	goto yy88;
		goto yy90;
	} else {
		if(yych <= '\'')	goto yy84;
		if(yych == '\\')	goto yy91;
		goto yy88;
	}
yy90:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy85;
	}
yy91:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy90;
	goto yy88;
yy92:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy93;
yy93:	if(yych <= '!'){
		if(yych == '\n')	goto yy90;
		goto yy92;
	} else {
		if(yych <= '"')	goto yy84;
		if(yych != '\\')	goto yy92;
		goto yy94;
	}
yy94:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy90;
	goto yy92;
}
#line 192 "scanner.re"


comment:

#line 598 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy95;
	if(yych <= ')'){
		if(yych == '\n')	goto yy100;
		goto yy102;
	} else {
		if(yych <= '*')	goto yy97;
		if(yych == '/')	goto yy99;
		goto yy102;
	}
	if(yych == '/')	goto yy105;
	goto yy98;
	if(yych == '*')	goto yy103;
	goto yy98;
	goto yy101;
	goto yy98;
	goto yy104;
	goto yy106;
	++YYCURSOR;
yy95:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= ')'){
		if(yych == '\n')	goto yy100;
		goto yy102;
	} else {
		if(yych <= '*')	goto yy97;
		if(yych == '/')	goto yy99;
		goto yy102;
	}
yy97:	yych = *++YYCURSOR;
	if(yych == '/')	goto yy105;
	goto yy98;
yy98:
#line 206 "scanner.re"
{ goto comment; }
#line 621 "scanner.c"
yy99:	yych = *++YYCURSOR;
	if(yych == '*')	goto yy103;
	goto yy98;
yy100:	yych = *++YYCURSOR;
	goto yy101;
yy101:
#line 202 "scanner.re"
{ if(cursor == s->eof) RETURN(0);
				  s->tok = s->pos = cursor; s->cline++;
				  goto comment;
				}
#line 633 "scanner.c"
yy102:	yych = *++YYCURSOR;
	goto yy98;
yy103:	yych = *++YYCURSOR;
	goto yy104;
yy104:
#line 200 "scanner.re"
{ ++depth;
				  goto comment; }
#line 642 "scanner.c"
yy105:	yych = *++YYCURSOR;
	goto yy106;
yy106:
#line 196 "scanner.re"
{ if(--depth == 0)
					goto scan;
				    else
					goto comment; }
#line 651 "scanner.c"
}
#line 207 "scanner.re"

}

void
Scanner_fatal(Scanner *s, const char *msg)
{
    fprintf(stderr, "line %d, column %d: %s\n", s->tline, s->tchar + 1, msg);
    exit(1);
}
