#!/bin/sh
splint \
 +allglobals \
 -noeffect \
 -exportlocal \
 -predbool \
 -boolops \
 +boolint \
 +charint \
 -retvalint \
 -retvalother \
 -shiftimplementation \
 -shiftnegative \
 +ansi89limits \
 -I/usr/local/include \
 -Isrc \
 -Isrc/arch/x86 \
 -I. \
 -DHAVE_CONFIG_H \
 -DHAVE_BOGUS_SYS_QUEUE_H \
 -Dlint \
 src/main.c \
 src/options.c \
 src/arch.c \
 src/bytecode.c \
 src/errwarn.c \
 src/expr.c \
 src/file.c \
 src/floatnum.c \
 src/globals.c \
 src/intnum.c \
 src/parser.c \
 src/section.c \
 src/arch/x86/x86arch.c \
 src/arch/x86/x86bc.c \
 src/arch/x86/x86expr.c \
 src/objfmts/dbg/dbg-objfmt.c \
 src/objfmts/bin/bin-objfmt.c \
 src/parsers/nasm/nasm-parser.c \
 src/preprocs/raw/raw-preproc.c \
 src/optimizers/basic/basic-optimizer.c \
 src/symrec.c \
 src/hamt.c
