# $Id$

TESTS += modules/arch/x86/tests/gas64/x86_gas64_test.sh

EXTRA_DIST += modules/arch/x86/tests/gas64/x86_gas64_test.sh
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-cbw.asm
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-cbw.errwarn
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-cbw.hex
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-inout.asm
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-inout.errwarn
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-inout.hex
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-movsxs.asm
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-movsxs.errwarn
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-movsxs.hex
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-muldiv.asm
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-muldiv.errwarn
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-muldiv.hex
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-retenter.asm
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-retenter.errwarn
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-retenter.hex
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-shift.asm
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-shift.errwarn
EXTRA_DIST += modules/arch/x86/tests/gas64/gas-shift.hex
EXTRA_DIST += modules/arch/x86/tests/gas64/riprel.asm
EXTRA_DIST += modules/arch/x86/tests/gas64/riprel.errwarn
EXTRA_DIST += modules/arch/x86/tests/gas64/riprel.hex

