# $Id$

TESTS += modules/arch/x86/tests/gas64/x86_gas64_test.sh

EXTRA_DIST += modules/arch/x86/tests/gas64/x86_gas64_test.sh
EXTRA_DIST += modules/arch/x86/tests/gas64/riprel.asm
EXTRA_DIST += modules/arch/x86/tests/gas64/riprel.errwarn
EXTRA_DIST += modules/arch/x86/tests/gas64/riprel.hex

