# $IdPath$

TESTS += \
	modules/arch/x86/tests/x86_test.sh

EXTRA_DIST += \
	modules/arch/x86/tests/x86_test.sh		\
	modules/arch/x86/tests/addbyte.asm		\
	modules/arch/x86/tests/addbyte.errwarn		\
	modules/arch/x86/tests/addbyte.hex		\
	modules/arch/x86/tests/addrop.asm		\
	modules/arch/x86/tests/addrop.errwarn		\
	modules/arch/x86/tests/addrop.hex		\
	modules/arch/x86/tests/addrop-err.asm		\
	modules/arch/x86/tests/addrop-err.errwarn	\
	modules/arch/x86/tests/cpubasic-err.asm		\
	modules/arch/x86/tests/cpubasic-err.errwarn	\
	modules/arch/x86/tests/div-err.asm		\
	modules/arch/x86/tests/div-err.errwarn		\
	modules/arch/x86/tests/effaddr.asm		\
	modules/arch/x86/tests/effaddr.errwarn		\
	modules/arch/x86/tests/effaddr.hex		\
	modules/arch/x86/tests/genopcode.asm		\
	modules/arch/x86/tests/genopcode.errwarn	\
	modules/arch/x86/tests/genopcode.hex		\
	modules/arch/x86/tests/lds-err.asm		\
	modules/arch/x86/tests/lds-err.errwarn		\
	modules/arch/x86/tests/loopadsz.asm		\
	modules/arch/x86/tests/loopadsz.errwarn		\
	modules/arch/x86/tests/loopadsz.hex		\
	modules/arch/x86/tests/mem64-err.asm		\
	modules/arch/x86/tests/mem64-err.errwarn	\
	modules/arch/x86/tests/mem64.asm		\
	modules/arch/x86/tests/mem64.errwarn		\
	modules/arch/x86/tests/mem64.hex		\
	modules/arch/x86/tests/negequ.asm		\
	modules/arch/x86/tests/negequ.errwarn		\
	modules/arch/x86/tests/negequ.hex		\
	modules/arch/x86/tests/nomem64-err.asm		\
	modules/arch/x86/tests/nomem64-err.errwarn	\
	modules/arch/x86/tests/nomem64.asm		\
	modules/arch/x86/tests/nomem64.errwarn		\
	modules/arch/x86/tests/nomem64.hex		\
	modules/arch/x86/tests/opersize.asm		\
	modules/arch/x86/tests/opersize.errwarn		\
	modules/arch/x86/tests/opersize.hex		\
	modules/arch/x86/tests/opsize-err.asm		\
	modules/arch/x86/tests/opsize-err.errwarn	\
	modules/arch/x86/tests/ret.asm			\
	modules/arch/x86/tests/ret.errwarn		\
	modules/arch/x86/tests/ret.hex			\
	modules/arch/x86/tests/segmov.asm		\
	modules/arch/x86/tests/segmov.errwarn		\
	modules/arch/x86/tests/segmov.hex		\
	modules/arch/x86/tests/shift.asm		\
	modules/arch/x86/tests/shift.errwarn		\
	modules/arch/x86/tests/shift.hex		\
	modules/arch/x86/tests/x86label.asm		\
	modules/arch/x86/tests/x86label.errwarn		\
	modules/arch/x86/tests/x86label.hex
