# $IdPath$

TESTS += \
	modules/preprocs/nasm/tests/nasmpp_test.sh

EXTRA_DIST += \
	modules/preprocs/nasm/tests/nasmpp_test.sh	\
	modules/preprocs/nasm/tests/ifcritical-err.asm	\
	modules/preprocs/nasm/tests/ifcritical-err.errwarn
