# $IdPath$

TESTS += \
	modules/objfmts/coff/tests/coff_test.sh

EXTRA_DIST += \
	modules/objfmts/coff/tests/coff_test.sh		\
	modules/objfmts/coff/tests/cofftest.c		\
	modules/objfmts/coff/tests/cofftest.asm		\
	modules/objfmts/coff/tests/cofftest.hex		\
	modules/objfmts/coff/tests/cofftest.errwarn
