# $Id$

TESTS += modules/objfmts/macho/tests/nasm64/macho64_test.sh

EXTRA_DIST += modules/objfmts/macho/tests/nasm64/macho64_test.sh
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/machotest64.c
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/machotest64.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/machotest64.hex
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/reloc64-err.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/reloc64-err.errwarn
