# $Id$

TESTS += modules/objfmts/elf/tests/amd64/elf_amd64_test.sh

EXTRA_DIST += modules/objfmts/elf/tests/amd64/elf_amd64_test.sh
EXTRA_DIST += modules/objfmts/elf/tests/amd64/elf-rip.asm
EXTRA_DIST += modules/objfmts/elf/tests/amd64/elf-rip.hex
EXTRA_DIST += modules/objfmts/elf/tests/amd64/elf-rip.errwarn
