# $Id$

TESTS += modules/objfmts/macho/tests/gas64/gas_macho64_test.sh

EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas_macho64_test.sh
EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas-macho64.asm
EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas-macho64.hex
