# $Id$

TESTS += modules/objfmts/win64/tests/win64_test.sh

EXTRA_DIST += modules/objfmts/win64/tests/win64_test.sh
EXTRA_DIST += modules/objfmts/win64/tests/win64-curpos.asm
EXTRA_DIST += modules/objfmts/win64/tests/win64-curpos.hex
EXTRA_DIST += modules/objfmts/win64/tests/win64-dataref.asm
EXTRA_DIST += modules/objfmts/win64/tests/win64-dataref.hex
EXTRA_DIST += modules/objfmts/win64/tests/win64-dataref.masm
EXTRA_DIST += modules/objfmts/win64/tests/win64-dataref2.asm
EXTRA_DIST += modules/objfmts/win64/tests/win64-dataref2.hex
EXTRA_DIST += modules/objfmts/win64/tests/win64-dataref2.masm
