# $Id$

TESTS += modules/objfmts/win64/tests/win64_test.sh

EXTRA_DIST += modules/objfmts/win64/tests/win64_test.sh
EXTRA_DIST += modules/objfmts/win64/tests/win64-dataref.asm
EXTRA_DIST += modules/objfmts/win64/tests/win64-dataref.hex
EXTRA_DIST += modules/objfmts/win64/tests/win64-dataref.errwarn
EXTRA_DIST += modules/objfmts/win64/tests/win64-dataref.masm
