# $Id$

TESTS += modules/arch/x86/tests/gas32/x86_gas32_test.sh

EXTRA_DIST += modules/arch/x86/tests/gas32/x86_gas32_test.sh
EXTRA_DIST += modules/arch/x86/tests/gas32/gas-movdq32.asm
EXTRA_DIST += modules/arch/x86/tests/gas32/gas-movdq32.errwarn
EXTRA_DIST += modules/arch/x86/tests/gas32/gas-movdq32.hex

