# $Id$

TESTS += modules/dbgfmts/dwarf2/tests/pass64/dwarf2_pass64_test.sh

EXTRA_DIST += modules/dbgfmts/dwarf2/tests/pass64/dwarf2_pass64_test.sh
EXTRA_DIST += modules/dbgfmts/dwarf2/tests/pass64/dwarf64_2loc.asm
EXTRA_DIST += modules/dbgfmts/dwarf2/tests/pass64/dwarf64_2loc.errwarn
EXTRA_DIST += modules/dbgfmts/dwarf2/tests/pass64/dwarf64_2loc.hex
EXTRA_DIST += modules/dbgfmts/dwarf2/tests/pass64/dwarf64_leb128.asm
EXTRA_DIST += modules/dbgfmts/dwarf2/tests/pass64/dwarf64_leb128.errwarn
EXTRA_DIST += modules/dbgfmts/dwarf2/tests/pass64/dwarf64_leb128.hex

