# $Id$

TESTS += modules/preprocs/raw/tests/rawpp_test.sh

EXTRA_DIST += modules/preprocs/nasm/tests/rawpp_test.sh
EXTRA_DIST += modules/preprocs/nasm/tests/longline.asm
EXTRA_DIST += modules/preprocs/nasm/tests/longline.hex
