# $IdPath$

TESTS += \
	modules/objfmts/win32/tests/win32_test.sh

EXTRA_DIST += \
	modules/objfmts/win32/tests/win32_test.sh	\
	modules/objfmts/win32/tests/win32test.c		\
	modules/objfmts/win32/tests/win32test.asm	\
	modules/objfmts/win32/tests/win32test.hex	\
	modules/objfmts/win32/tests/win32test.errwarn
