# $Id$

TESTS += modules/parsers/gas/tests/gas_test.sh

EXTRA_DIST += modules/parsers/gas/tests/gas_test.sh
EXTRA_DIST += modules/parsers/gas/tests/datavis.asm
EXTRA_DIST += modules/parsers/gas/tests/datavis.errwarn
EXTRA_DIST += modules/parsers/gas/tests/datavis.hex
EXTRA_DIST += modules/parsers/gas/tests/datavis2.asm
EXTRA_DIST += modules/parsers/gas/tests/datavis2.errwarn
EXTRA_DIST += modules/parsers/gas/tests/datavis2.hex
EXTRA_DIST += modules/parsers/gas/tests/jmpcall.asm
EXTRA_DIST += modules/parsers/gas/tests/jmpcall.errwarn
EXTRA_DIST += modules/parsers/gas/tests/jmpcall.hex
EXTRA_DIST += modules/parsers/gas/tests/reggroup-err.asm
EXTRA_DIST += modules/parsers/gas/tests/reggroup-err.errwarn
EXTRA_DIST += modules/parsers/gas/tests/reggroup.asm
EXTRA_DIST += modules/parsers/gas/tests/reggroup.errwarn
EXTRA_DIST += modules/parsers/gas/tests/reggroup.hex

