# $IdPath$

TESTS += modules/objfmts/coff/tests/coff_test.sh

EXTRA_DIST += modules/objfmts/coff/tests/coff_test.sh
EXTRA_DIST += modules/objfmts/coff/tests/cofftest.c
EXTRA_DIST += modules/objfmts/coff/tests/cofftest.asm
EXTRA_DIST += modules/objfmts/coff/tests/cofftest.hex
EXTRA_DIST += modules/objfmts/coff/tests/cofftest.errwarn
