# $Id$

TESTS += modules/objfmts/macho/tests/nasm32/macho32_test.sh

EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho32_test.sh
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/machotest.c
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/machotest.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/machotest.hex
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho-reloc.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho-reloc.hex
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho-sect.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho-sect.errwarn
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho-sect.hex
